/*
 * AUTO-GENERATED by scripts/generate_version.sh from the git-ignored
 * version.txt at the project root. Do not edit by hand.
 *
 * Committed with fallback values (1.0.0 / build 1) for fresh checkouts and
 * CI; the build overwrites it in place whenever version.txt differs.
 */
#ifndef FIRMWARE_VERSION_GENERATED_H
#define FIRMWARE_VERSION_GENERATED_H

#define FIRMWARE_VERSION "1.0.0"
#define FIRMWARE_BUILD "1"

#endif /* FIRMWARE_VERSION_GENERATED_H */
