#!/usr/bin/env bash
#
# generate_version.sh <swift|c> <output-file>
#
# Central version generator. Reads the git-ignored version.txt at the
# project root (line 1: version, line 2: build number) and writes a small
# generated source/header with the values baked in at build time:
#
#   swift -> ObsStatusVersion.swift   (macOS app, via the SwiftPM build
#                                      tool plugin and the Xcode run script)
#   c     -> firmware_version_generated.h (ESP32 firmware, via CMake)
#
# Both consumers fall back to 1.0.0 / build 1 when version.txt is missing
# or malformed, so fresh checkouts and CI keep building.

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "usage: $0 <swift|c> <output-file>" >&2
    exit 1
fi

kind=$1
output=$2

case "$kind" in
    swift|c) ;;
    *)
        echo "generate_version: unknown kind '$kind' (expected 'swift' or 'c')" >&2
        exit 1
        ;;
esac

project_root=$(cd "$(dirname "$0")/.." && pwd)
version_file=$project_root/version.txt

version="1.0.0"
build="1"

if [ -f "$version_file" ]; then
    file_version=$(sed -n '1p' "$version_file" | tr -d '[:space:]')
    file_build=$(sed -n '2p' "$version_file" | tr -d '[:space:]')
    if printf '%s' "$file_version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.]+)?$'; then
        version=$file_version
    else
        echo "generate_version: invalid version '$file_version', falling back to $version" >&2
    fi
    if printf '%s' "$file_build" | grep -Eq '^[0-9]+$'; then
        build=$file_build
    else
        echo "generate_version: invalid build number '$file_build', falling back to $build" >&2
    fi
fi

mkdir -p "$(dirname "$output")"

if [ "$kind" = "swift" ]; then
    cat > "$output" <<EOF
//
//  ObsStatusVersion.swift
//
//  AUTO-GENERATED by scripts/generate_version.sh from the git-ignored
//  version.txt at the project root. Do not edit by hand.
//

/// Build-time version and build number for the macOS app.
enum ObsStatusVersion {
    static let version = "$version"
    static let build = "$build"

    /// "1.0.0 (1)"
    static var display: String { "\(version) (\(build))" }
}
EOF
else
    cat > "$output" <<EOF
/*
 * AUTO-GENERATED by scripts/generate_version.sh from the git-ignored
 * version.txt at the project root. Do not edit by hand.
 *
 * This file is git-ignored; every firmware build regenerates it in place,
 * falling back to 1.0.0 / build 1 when version.txt is absent.
 */
#ifndef FIRMWARE_VERSION_GENERATED_H
#define FIRMWARE_VERSION_GENERATED_H

#define FIRMWARE_VERSION "$version"
#define FIRMWARE_BUILD "$build"

#endif /* FIRMWARE_VERSION_GENERATED_H */
EOF
fi
