#!/usr/bin/env bash
#
# generate_version.sh <swift|c|plist> <output-file> [version-file]
#
# Central version generator. Reads the git-ignored version.txt at the
# project root (line 1: version, line 2: build number) and emits the values
# in the shape each build needs:
#
#   swift -> ObsStatusVersion.swift  (SwiftPM build tool plugin for
#                                     swift build / swift test; the Xcode
#                                     app gets the values in its Info.plist
#                                     instead, via the plist kind)
#   c     -> firmware_version_generated.h (ESP32 firmware)
#   plist -> patches an Info.plist in place (the Xcode run script bakes the
#            values into the built app bundle before code signing)
#
# All consumers fall back to 1.0.0 / build 1 when version.txt is missing
# or malformed, so fresh checkouts and CI keep building.

set -euo pipefail

if [ $# -ne 2 ] && [ $# -ne 3 ]; then
    echo "usage: $0 <swift|c|plist> <output-file> [version-file]" >&2
    exit 1
fi

kind=$1
output=$2

project_root=$(cd "$(dirname "$0")/.." && pwd)
if [ $# -eq 3 ]; then
    version_file=$3
else
    version_file=$project_root/version.txt
fi

version="1.0.0"
build="1"

if [ -f "$version_file" ]; then
    file_version=$(sed -n '1p' "$version_file" | tr -d '[:space:]')
    file_build=$(sed -n '2p' "$version_file" | tr -d '[:space:]')
    if printf '%s' "$file_version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.]+)?$'; then
        version=$file_version
    else
        echo "generate_version: invalid version '$file_version', falling back to $version" >&2
    fi
    if printf '%s' "$file_build" | grep -Eq '^[0-9]+$'; then
        build=$file_build
    else
        echo "generate_version: invalid build number '$file_build', falling back to $build" >&2
    fi
fi

case "$kind" in
    swift|c|plist) ;;
    *)
        echo "generate_version: unknown kind '$kind' (expected 'swift', 'c' or 'plist')" >&2
        exit 1
        ;;
esac

if [ "$kind" = "plist" ]; then
    if [ ! -f "$output" ]; then
        echo "generate_version: Info.plist '$output' does not exist yet" >&2
        exit 1
    fi
    /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $version" "$output"
    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $build" "$output"
    exit 0
fi

mkdir -p "$(dirname "$output")"

if [ "$kind" = "swift" ]; then
    cat > "$output" <<EOF
//
//  ObsStatusVersion.swift
//
//  AUTO-GENERATED by scripts/generate_version.sh from the git-ignored
//  version.txt at the project root. Do not edit by hand.
//

/// Build-time version and build number for the macOS app.
enum ObsStatusVersion {
    static let version = "$version"
    static let build = "$build"

    /// "1.0.0 (1)"
    static var display: String { "\(version) (\(build))" }
}
EOF
else
    cat > "$output" <<EOF
/*
 * AUTO-GENERATED by scripts/generate_version.sh from the git-ignored
 * version.txt at the project root. Do not edit by hand.
 *
 * This file is git-ignored; every firmware build regenerates it in place,
 * falling back to 1.0.0 / build 1 when version.txt is absent.
 */
#ifndef FIRMWARE_VERSION_GENERATED_H
#define FIRMWARE_VERSION_GENERATED_H

#define FIRMWARE_VERSION "$version"
#define FIRMWARE_BUILD "$build"

#endif /* FIRMWARE_VERSION_GENERATED_H */
EOF
fi
